import { createApp } from "vue";
import App from "./App.vue";
import router from "./router";
import store from "./store";
import "@/assets/style.css";
import appHeader from "@/components/appHeader";
import appFooter from "@/components/appFooter";
import appCountdown from "@/components/appCountdown";
import appTestPagination from "@/components/appTestPagination";
import appQuestionSwitchButtons from "@/components/appQuestionSwitchButtons";
import appModal from "@/components/appModal";
import VueCountdown from "@chenfengyuan/vue-countdown";
const app = createApp(App);
app.use(store);
app.use(router);
app.component("AppHeader", appHeader);
app.component("AppFooter", appFooter);
app.component("AppCountdown", appCountdown);
app.component("AppTestPagination", appTestPagination);
app.component("AppQuestionSwitchButtons", appQuestionSwitchButtons);
app.component("AppModal", appModal);
app.component(VueCountdown.name, VueCountdown);
app.mount("#app");
